### ISSUE TITLE
Make docker image that fronts node with nginx

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#115]
As an operator I would like more efficient gzipping, and caching than nodejs can provide.

**Comment by bennett000** [comment]
update, as per @bertrandk's suggestion we need to look into node/passenger, and even passenger's docker stuff.  This might help us speed up deployment. https://github.com/phusion/passenger-docker#why_use

Unrelated, but on the speed front we might consider placing our Ec2's into some sort of "object pool" type structure to avoid destroying the host containers... that's a whole other issue though.

**Comment by bennett000** [comment]
There are some more details at this link https://hub.docker.com/r/phusion/passenger-nodejs/

Configuring one of these passenger dockers is a _little_ different than configuring a normal docker, since the passenger people have made things "convenient".  This includes an SSH server.  

Since we are going to be including people's public SSH keys in the `./private/ssh-public` folder the Docker instances _will_ have access to the keys, and they can be easily installed either through passenger's systems, or our `serve.sh` script

Actually passenger _might_ even have a solution that gets us out of needing a `serve.sh` script

**Comment by bertrandk** [comment]
Two things occur to me though I don't know if they're germane to this issue.

1) Their README has a duplicate section :laughing: 
![](https://cldup.com/THiozGXdZ1.png)

2) I've noticed a tendency to build or rebuild applications in the production environment. The problem is that when `NODE_ENV` === `production`, [npm will not install `devDependencies`](https://docs.npmjs.com/misc/config#production) – many of which are usually build dependencies. You don't want to change the `NODE_ENV` because you'll want it set to `production` during runtime. As a result, it's been customary to [set `NPM_CONFIG_PRODUCTION=false` in Heroku]( https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process). You can also imagine running installs as follows: `$ NODE_ENV=development npm install` and ostensibly only override the env var for that one invocation. Others simply treat build deps as normal deps. There's many ways this can be done and so it is done many ways. A default that just works would be nice here.

I'm mostly thinking out loud here but just yesterday, a team ran into this issue while setting up their deployments. It took all of 2 min to resolve but I rather not have to do it at all.

**Comment by bennett000** [comment]
@bertrandk sorry I missed this back in November.  

To address your second point, the way clusternator's docker containers running node services are built _without `NODE_ENV`_.  We only set `NODE_ENV` when the Docker container is instantiated.  This way it's possible to run a given container with `NODE_ENV=production` or `NODE_ENV=staging`, or `NODE_ENV=debug`, which can be handy when debugging.

To your first point, the last time I looked at Passenger they were running node ~0.12.x, and we want to use 4.2.3 (4.2.4 as of yesterday).  We might consider submitting PR's to Docker/Passenger in the future, but I haven't really played with their Docker stuff yet.
