### ISSUE TITLE
as a clusternator user I would like my URLs to have zero down time

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#294]
Currently when PR's are updated or when deployments are updated they tear down, then rebuild.  They really need to rebuild and flip the DNS when the new instance has reached a steady state.

Due to the way Clusternator implements tagging there is a fair bit to this.  Please ask @bennett000 directly for details

**Comment by SethDavenport** [comment]
@bennett000 As discussed, another idea would be to re-use the same ELB and just update what's behind it.  This should not only speed up the deployment, but eliminate the DNS issue entirely because the CNAME would never change once created.

We'd want to do this not only when updating master but also when updating an existing PR.

**Comment by bennett000** [comment]
Preserving the ELB is gold.  I love it.   We just need to sort out the implementation details, which is essentially fixing/improving the current code so that it has update logic instead of destroy->re-create fake update logic.

**Comment by SethDavenport** [comment]
I feel like we should be able to preserve almost everything - CNAME, ELB, and EC2 hosts.  It's just the docker images that need updating right?  Or am I not understanding how ECS works?

**Comment by SethDavenport** [comment]
Update code works, teardown code needs a bit more work.
